### ISSUE TITLE
Umwandlung in relative Links arbeitet nicht korrekt

### ISSUE THREAD

**Issue by JanRei** [xwolfde/Piratenkleider#205]
Ich habe WordPress 4.2.1 mit Piratenkleider-Theme unter `https://localhost/wordpress` installiert.
1. In einem Beitrag ist ein Bild eingebunden mit der URL `https://localhost/wordpress/wp-content/uploads/2015/04/Bild.png`. Auf der Startseite wird das Bild jedoch nicht angezeigt. Anscheinend wird versucht, die absolute URL in eine relative URL umzuwandeln. Im Seitenquelltext steht nämlich die URL `/wp-content/uploads/2015/04/Bild.png`, was in meinem Fall der absoluten URL `https://localhost/wp-content/uploads/2015/04/Bild.png` entspricht. Das Unterverzeichnis "wordpress" ist verloren gegangen und die Bilddatei kann nicht gefunden werden.
2. Etwas ähnliches passiert bei relativen Links wie `/wordpress/?p=1`. Hieraus wird `/?p=1`.
3. Links wie `http://localhost/wordpress/?p=1` werden mit einem Doppelpfeil-Symbol als externe Links gekennzeichnet. Vielleicht sollte das Protokoll (HTTP oder HTTPS) bei so etwas ignoriert werden.

**Comment by xwolfde** [comment]
Hm... Ist der Einsatz von ganzen Webauftritten innerhalb von Verzeichnissen überhaupt noch zeitgemäß? 
Alle genannten Probleme ergeben sich nur daraus, dass die Installation Directory-based und nicht Domain-based  ist. Ehrlich gesagt sehe ich den Nutzen nicht, solche Installationen zu unterstützen...

**Comment by JanRei** [comment]
Ich kann nicht beurteilen, ob eine solche Konfiguration häufig vorkommt. Aber meiner Meinung nach sollte Piratenkleider keine Links kaputt machen, die sonst funktionieren würden.

**Comment by xwolfde** [comment]
Repariere es doch :) 
Nachdem das Theme nun bereits seit 2012 so in Betrieb ist und es bislang keine derartige Problemmeldung gab, sehe ich da kein Bedarf, es auf "Directory Based" Installationen anzupassen.

**Comment by xwolfde** [comment]
Oh, Merge hat leider ein Bug @JanRei  
"Warning: DOMDocument::loadHTML(): Empty string supplied as input in.../wp-content/themes/Piratenkleider/functions.php on line 1611"

**Comment by xwolfde** [comment]
(habs gefixt)

**Comment by xwolfde** [comment]
Hm, also alle Links werden davon aber nun nicht mehr relativ?
vgl. piratenkleider.de

**Comment by JanRei** [comment]
Welche Links meinst du genau?

Eigentlich sollten in etwa die gleichen Links wie bisher relativ gemacht werden. Meine Herangehensweise müsste zuverlässiger die zu ersetzenden Links finden, hat dafür aber ein paar zusätzliche Stolpersteine. Vielleicht habe ich davon noch nicht alle gefunden.

**Comment by xwolfde** [comment]
Im Bereich unten zu content-aside.
Aber ich weiss nicht ob das nicht vorher schon so war.
Der Bereich kommt nicht aus der content eines posts.

**Comment by JanRei** [comment]
Oberhalb von content-aside sind die Links zu weiteren Meldungen. Diese werden wahrscheinlich nicht relativ gemacht, weil der Filter post_link in der Funktion rw_relative_urls auskommentiert ist. Hier habe ich nichts geändert.

Innerhalb von content-aside ist der Slider. Die in den Einstellungen ausgewählten Bilder werden direkt mit der absoluten URL gespeichert und auch so ausgegeben. Auch hier habe ich nichts geändert. Ich bin mir nicht sicher, wie man diese URLs elegant relativ machen könnte.

**Comment by xwolfde** [comment]
ich hab die Funktionen für relative links erstmal deaktiviert.
