### ISSUE TITLE
Untermenüs in der mobilen Ansicht

### ISSUE THREAD

**Issue by throwException** [xwolfde/Piratenkleider#214]
Die Untermenüs erscheinen in der mobilen Ansicht nicht, wodurch ein guter Teil der Seite nicht erreichbar ist.

**Comment by J0WI** [comment]
Scheint bei piratenpartei.de zu funktionieren. Ich habe mal die Einstellungen geprüft aber nichts dergleichen gefunden.

**Comment by throwException** [comment]
Habs gefunden. Nennt sich Hamburger-Menü.
