### ISSUE TITLE
Option "Kommentare beantworten" ist verwirrend und "doppelt gemoppelt"

### ISSUE THREAD

**Issue by JustThomas** [xwolfde/Piratenkleider#216]
In den allgemeinen WordPress-Einstellungen unter "Einstellungen -> Diskussion" kann man wählen, ob WordPress verschachtelte Kommentare erlauben soll und in wie vielen Ebenen.

![Screenshot WordPress-Backend](https://cloud.githubusercontent.com/assets/1545787/8507322/5e627eec-223e-11e5-9038-a3058d5243b9.png)

Allerdings genügt es nicht, die verschachtelten Kommentare dort zu aktivieren, weil es in den Theme-Optionen der Piratenkleider zusätzlich die Option "Kommentare beantworten" gibt. Erst wenn auch dort der Haken gesetzt ist, funktionieren die verschachtelten Kommentare.

![Screenshot Theme-Optionen](https://cloud.githubusercontent.com/assets/1545787/8507329/90bfbdb4-223e-11e5-90cc-50f2899fc6f6.png)

Das ist verwirrend für User, die verschachtelte Kommentare in den WordPress-Einstellungen aktiviert haben, aber die "Kommentare beantworten"-Option in den Theme-Einstellungen nicht kennen oder übersehen haben.

Ich schlage vor, diese Theme-Option aus dem Backend zu entfernen und stattdessen einfach zu prüfen, ob verschachtelte Kommentare aktiviert sind oder nicht.

**Comment by xwolfde** [comment]
Äh, nee, das ist nichts was die Verschachtelung angeht, also die Optik, sondern das sorgt dafür, daß der Button "Auf Kommentar antworten" angezeigt wird.

**Comment by JustThomas** [comment]
OK, verstehe. Das hatte bei uns zu Verwirrung geführt.

Ich hatte das Ticket aufgemacht, nachdem bei uns in der BayernIT eine Anfrage kam:
> eigentlich [tm] sollten mit Wordpress verschachtelte Kommentare [1] möglich sein (incl. einem Link 'antworten' unter jedem bereits existierenden Kommentar). Die Option " Verschachtelte Kommentare in 4 Ebenen organisieren" ist aktiviert. Allerdings funktioniert es nicht

Und nachdem ich die "Kommentare beantworten"-Option gesetzt habe, hieß es dann:
> danke dir, funktioniert wunderbar!

**Comment by xwolfde** [comment]
Das war auch nur so eine Funktion die aus einen Speziellen Userwunsch hervorging :=P 


By the way: Ihr könnt dann bei Gelegenheit auf 3.3.17 updaten. Die ist dann nämlich WP 4.4 ready.

Oder gleich auf den Branch 3.4; Aber das soll eigentlich nur ein Entwicklungsbranch werden, in der ich dann alle merges sammle um dann erst von da zum Master zu mergen, wenn dort wieder ein Release kommen soll.
