### ISSUE TITLE
Update mechanism

### ISSUE THREAD

**Issue by J0WI** [xwolfde/Piratenkleider#231]
It would be **so much easier** if you could use the update mechanism of Wordpress to update the theme.

**Comment by xwolfde** [comment]
They dont want to add the theme into the wordpress theme directory, cause it contains functions that are so called plugin domains :/ I tried it three times already. Fixed this, fixed that, and then at last they came up with this reason...

But cause this problem hit many others too, there is a plugin that allows to update from github repos:
https://github.com/afragen/github-updater

**Comment by J0WI** [comment]
Could you specify what plugin domain functions mean?

**Comment by xwolfde** [comment]
"plugin domain": The theme contains functions, that should be transfered into plugins. See also results from theme tester plugin.

**Comment by xwolfde** [comment]
GitHub Updater sollte mit der nächsten version gehen
