### ISSUE TITLE
Add EditorConfig

### ISSUE THREAD

**Issue by J0WI** [xwolfde/Piratenkleider#232]
@xwolfde, your changes in d92bb265f87e6d657542e35d82b917f3576f4ab8 uses dos linebreaks again.
Would you like to fix them?

**Comment by xwolfde** [comment]
Hu?
On MacOS i cannot see them, nor get problems after sync. On my windows client i use netbeans in unix mode to edito files and transfer them to a linux server for testing without problems..
Also on MacOS.
Normally the github-client uses ascii-mode for transfering files of this type.  Are you using this github-client?

**Comment by J0WI** [comment]
I use git and vim on console.

**Comment by J0WI** [comment]
```$ file css/piratenkleider.css```
css/piratenkleider.css: ASCII text, with very long lines, **with CRLF line terminators**
```$ dos2unix css/piratenkleider.css```
dos2unix: Datei css/piratenkleider.css wird ins Unix-Format umgewandelt ...
```$ file css/piratenkleider.css```
css/piratenkleider.css: ASCII text, with very long lines

**Comment by J0WI** [comment]
You should use an [EditorConfig](http://editorconfig.org/) or similar to get rid of such code style issues.

**Comment by xwolfde** [comment]
i am working on unix, win and macos clients with the same config and cannot confirm any of your statements. 
Please test your config.
