### ISSUE TITLE
Contact Form 7

### ISSUE THREAD

**Issue by ukcb** [xwolfde/Piratenkleider#251]
Die Piratenkleider scheinen nicht mit dem Plugin Contact Form 7
https://wordpress.org/plugins/contact-form-7/ klarzukommen. 
Ich habe hier WP 4.8.3 und CF7 4.9.1.
Kannst du bitte mal checken, ob es ein Problem gibt und wer den Schwarzen Peter bekommt?
Bei Pirate-Rogue funktioniert CF7. Problem: habe etliche Instanzen mit Piratenkleidern laufen.

**Comment by webotop** [comment]
Dunno what is the problem but use something else than contact form 7... I do love Contact Form By Supsystic tho.

**Comment by ukcb** [comment]
In CR7 findet man

`if ( strlen( $user_agent ) < 2 ) { $spam = true; }`

In den Piratenkleidern in functions.php

`if ($options['anonymize-user']==1) { $_SERVER["HTTP_USER_AGENT"] = ""; }`

Unter der bestimmten Bedingung wird die Nachricht als Spam eingestuft.
Abhilfe kann ein UserAgent mit mindestens 2 Zeichen schaffen.

`if ($options['anonymize-user']==1) { $_SERVER["HTTP_USER_AGENT"] = "ua"; }`

Hilft hier schon. Wäre nett wenn du so etwas einbauen würdest. Danke.

**Comment by xwolfde** [comment]
ok, neue Version ist im Git
