### ISSUE TITLE
Menüleiste bei mobilen Browsern nicht korrekt

### ISSUE THREAD

**Issue by knarfbb** [xwolfde/Piratenkleider#254]
Menüleiste wird z.B. auf piratenpotsdam.de unter iOS (Safari und chrome) hinter der Headline versteckt. Kann man mit runter ziehen sichtbar machen, man kann aber nichts anklicken, da bei loslassen die Leiste sofort wieder wegrutscht. Bei Android wird die Leiste wohl gar nicht angezeigt, Headline scheint aber dafür Oberen Bildteil zu überdecken.

**Comment by xwolfde** [comment]
Verschoben nach Pirate-Rogue https://github.com/Piratenpartei/Pirate-Rogue/issues/215
